package gui;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

public class AboutMe extends javax.swing.JFrame {
    
    private static AboutMe instance;
    
    public static AboutMe getInstance(){
        if(instance == null){
            instance = new AboutMe();
        }
        
        return instance;
    }

    private AboutMe() {
        initComponents();
        
        style();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        githubButton = new javax.swing.JButton();
        linkedinButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 250));

        jPanel1.setBackground(new java.awt.Color(255, 255, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mail.png"))); // NOI18N
        jLabel2.setText("       Email: thecoolestdeveloper@gmail.com");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 108, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/linkedin.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/github.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 192, -1, -1));

        jPanel2.setBackground(new java.awt.Color(24, 118, 208));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATOS DE CONTACTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        githubButton.setBackground(new java.awt.Color(0, 51, 255));
        githubButton.setForeground(new java.awt.Color(0, 51, 255));
        githubButton.setText("GitHub");
        githubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githubButtonActionPerformed(evt);
            }
        });
        jPanel1.add(githubButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        linkedinButton.setBackground(new java.awt.Color(0, 51, 255));
        linkedinButton.setForeground(new java.awt.Color(0, 51, 255));
        linkedinButton.setText("LinkedIn");
        linkedinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkedinButtonActionPerformed(evt);
            }
        });
        jPanel1.add(linkedinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linkedinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkedinButtonActionPerformed
        // TODO add your handling code here:
        openUrl("https://www.linkedin.com/in/hector-eduardo-aguilar/");
    }//GEN-LAST:event_linkedinButtonActionPerformed

    private void githubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githubButtonActionPerformed
        // TODO add your handling code here:
        openUrl("https://github.com/plapis");
    }//GEN-LAST:event_githubButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton githubButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton linkedinButton;
    // End of variables declaration//GEN-END:variables

    private void style() {
        githubButton.setOpaque(false);
        githubButton.setContentAreaFilled(false); 
        githubButton.setBorderPainted(false); 
        
        linkedinButton.setOpaque(false);
        linkedinButton.setContentAreaFilled(false); 
        linkedinButton.setBorderPainted(false); 
    }

    private void openUrl(String url) {
        try {
         
        Desktop.getDesktop().browse(new URI(url));
         
        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }
}
