package gui;

import acciones.TareaAcciones;
import clases.TareaClass;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Historial extends javax.swing.JFrame {

    private static Historial historial;
    
    public static Historial obtenInstancia(){
        if(historial == null){
            historial = new Historial();
        }
        return historial;
    }
    
    ArrayList <TareaHistorial> tareasList = new ArrayList<>(); 

    private Historial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tar = new javax.swing.JScrollPane();
        tareasPanel = new javax.swing.JPanel();

        setTitle("Historial de tareas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tareasPanel.setBackground(new java.awt.Color(43, 41, 41));
        tareasPanel.setLayout(new javax.swing.BoxLayout(tareasPanel, javax.swing.BoxLayout.Y_AXIS));
        tar.setViewportView(tareasPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tar, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tar, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cargaTareas();
    }//GEN-LAST:event_formWindowOpened



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane tar;
    protected javax.swing.JPanel tareasPanel;
    // End of variables declaration//GEN-END:variables

    
    private void cargaTareas() {
        try {
            ArrayList<TareaClass> tareas = TareaAcciones.obtenerTareasHistoria();
            tareasList.clear();
            tareasPanel.removeAll();
            for(TareaClass tarea: tareas){
                TareaHistorial tareaHistorial = new TareaHistorial(tarea);
                tareasList.add(tareaHistorial);
                tareasPanel.add(tareaHistorial);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
    
    void eliminarTarea(TareaHistorial tarea) {
        tareasList.remove(tarea);
        tareasPanel.remove(tarea);
        tareasPanel.validate();
    }

    void mostrar() {
        cargaTareas();
        setVisible(true);
        requestFocus();
        validate();
    }    
}
